### PR TITLE
Sheetsee Upgrade

### PR DESCRIPTION
**Pull request by deltamualpha**
So, this upgrades sheetsee and simplifies some of the functionality in the `showdata()` function, but at the cost of losing the color-changing on selection of markers. The map also no longer "clusters" nearby markers together, but I believe that's because of a change in sheetsee.js, not in hack-spots specifically.

Two bugs I came across: highlightLastMarker() was highlighting the _oldest_ marker instead of the newest, and the latest version of sheetsee.js on npm double-renders tables (resulting in an empty table) if you don't pass its pagination option.

I also standardized the indentation style around four spaces; sorry if that's not preferred, but it had been a mix of spaces and tabs and this at least is consistent.

### CODE REVIEW

**Comment by deltamualpha** [comment]
Should I file a bug against https://github.com/jlord/sheetsee-tables for the double-rendering issue, @jlord?

**Comment by jlord** [comment]
Sorry about the delay on this!

re: indents, no worries, the fix is appreciated, I had a confused editor and never updated this, so it needed it!

I ran into the clustering problem myself when I tried to update the sheetsee. It's definitely a bummer because the clustering was useful. But I'm willing to live without it for a bit until I can figure out what's up there.

I noticed though that the zoom doesn't work, any thoughts on that?

I'll go ahead and open an issue on `sheetsee-tables`, that definitely needs to get fixed!

**Comment by deltamualpha** [comment]
With zoom, it was unclear to me what the behavior was supposed to be. The version of the map I'd seen had the clustering, which sort of handled zoom automatically?

Right now it's defaulting to zoom level 0 on map load (and reset) and then not zooming at all on interaction with the table (obviously). I think it should zoom to the pin when you click on a table row, but not zoom when you click on a pin. Is there built-in functionality in sheetsee or the mapbox API to zoom to a "see all pins on this layer" level, which would make sense for initial load and reset? I couldn't find it from a cursory search.

**Comment by jlord** [comment]
I found the correct zoom method `map.setView([lat, long], zoom)` so I'll merge this then add that in :+1: 

Thanks so much for your work! It's super helpful. Hopefully I'll get the rest of it updated sometime soon!

**Pull request merged**
